import express from "express";
import userRouter from "./routes/userRoutes.js";
import { corsMiddleware } from "./middlewares/cors.js";
import cors from "cors";
import swaggerUi from "swagger-ui-express";
import swaggerDocument from "./docs/swagger.json" assert { type: "json" };
import productRouter from "./routes/productRoutes.js";
import salesRouter from "./routes/salesRoutes.js";

export const app = express();
app.disable("x-powered-by");
app.use(express.json("5mb"));
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.get("/", (req, res) => res.redirect("/docs"));
app.use('/static', express.static('public'));
app.use("/users", userRouter);
app.use("/products", productRouter);
app.use("/sales", salesRouter);
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));
